from ewelink.mixins.methods import (
    check_device_update,
    check_devices_updates,
    get_credentials,
    get_device,
    get_device_channel_count,
    get_device_current_humidity,
    get_device_current_temperature,
    get_device_current_th,
    get_device_ip,
    get_device_power_state,
    get_device_power_usage,
    get_device_power_usage_raw,
    get_devices,
    get_firmware_version,
    get_region,
    get_ws_device_power_state,
    get_ws_device_status,
    init_device_control,
    make_request,
    open_websocket,
    save_devices_cache,
    set_device_power_state,
    set_ws_device_power_state,
    toggle_device,
    update_device_status,
    web_socket_close,
    web_socket_handshake,
)

_MIXIN_FUNCTIONS = [
    check_devices_updates,
    check_device_update,
    init_device_control,
    web_socket_handshake,
    web_socket_close,
    update_device_status,
    get_ws_device_status,
    get_ws_device_power_state,
    set_ws_device_power_state,
    get_credentials,
    get_device,
    get_device_channel_count,
    get_device_current_th,
    get_device_current_temperature,
    get_device_current_humidity,
    get_device_ip,
    get_device_power_state,
    get_device_power_usage,
    get_device_power_usage_raw,
    get_devices,
    get_firmware_version,
    get_region,
    make_request,
    open_websocket,
    save_devices_cache,
    set_device_power_state,
    toggle_device,
]


_CAMEL_ALIASES = {
    "check_devices_updates": "checkDevicesUpdates",
    "check_device_update": "checkDeviceUpdate",
    "init_device_control": "initDeviceControl",
    "web_socket_handshake": "webSocketHandshake",
    "web_socket_close": "webSocketClose",
    "update_device_status": "updateDeviceStatus",
    "get_ws_device_status": "getWSDeviceStatus",
    "get_ws_device_power_state": "getWSDevicePowerState",
    "set_ws_device_power_state": "setWSDevicePowerState",
    "get_credentials": "getCredentials",
    "get_device": "getDevice",
    "get_device_channel_count": "getDeviceChannelCount",
    "get_device_current_th": "getDeviceCurrentTH",
    "get_device_current_temperature": "getDeviceCurrentTemperature",
    "get_device_current_humidity": "getDeviceCurrentHumidity",
    "get_device_ip": "getDeviceIP",
    "get_device_power_state": "getDevicePowerState",
    "get_device_power_usage": "getDevicePowerUsage",
    "get_device_power_usage_raw": "getDevicePowerUsageRaw",
    "get_devices": "getDevices",
    "get_firmware_version": "getFirmwareVersion",
    "get_region": "getRegion",
    "make_request": "makeRequest",
    "open_websocket": "openWebSocket",
    "save_devices_cache": "saveDevicesCache",
    "set_device_power_state": "setDevicePowerState",
    "toggle_device": "toggleDevice",
}


def apply_mixins(target_cls):
    for func in _MIXIN_FUNCTIONS:
        setattr(target_cls, func.__name__, func)
        alias = _CAMEL_ALIASES.get(func.__name__)
        if alias:
            setattr(target_cls, alias, func)
